### ISSUE TITLE
Kodi Support

### ISSUE THREAD

**Issue by khalidl** [Amelandbor/service.subtitles.nlondertitels#1]
@Amelandbor Any chance of updating this to work with Kodi? Would be much appreciated.

**Comment by Amelandbor** [comment]
It's working here on Kodi. Could you describe what's not working on your end?

**Comment by khalidl** [comment]
Searching for subtitles works perfectly fine, when selecting a subtitle to download it displays the following message: `Downloading subtitles…` › `Failed to download subtitle. Download didn’t contain a subtitle file`.

I’m using Kodi (14.0) on a Mac.

**Comment by Amelandbor** [comment]
After looking into it, it has nothing to do with the version of Kodi you're using. 
It shouldn't happen with every file.
It has to do with the way Kodi handles zip/rar files. The intention from Kodi is to move to another library which can handle more file formats and more variations of zip and rar files.

**Comment by khalidl** [comment]
Just tested again with archives it downloads as rar and zip. When I head over to `Kodi › userdata › addon_data › service.subtitles.nlondertitels`, I can see there is a `temp` folder. 

**RAR**
Within the `temp` folder is **nlondertitel.rar** and the extracted archive as folder. 
That last folder holds the sub and a releases.txt file. 

**ZIP**
Within the `temp` folder is **nlondertitel.zip**, but it’s not extracted.

So it is downloading and extracting successfully (rar), but doesn’t move the subtitle to the appropriate location.

What would be a possible solution? Why is it working for you, but not for me?

**Comment by Amelandbor** [comment]
Could you post the movie and subtitle version you're trying to download? 
Extracting is hit or miss for now, but if it's extracted I should be able to find a solution.

**Comment by khalidl** [comment]
**Movie**: The Boxtrolls
**Subtitles**: There are four listed; all produce the same result/bug.

**Comment by Amelandbor** [comment]
Pushed a fix for the subfolder problem, so this way the second version of the subtitle should at least work.

**Comment by khalidl** [comment]
Excellent! This fixes this issue for me. I’ve tested it on a couple of other movies, and all gets processed correctly. 

Thanks @Amelandbor! :+1:

**Comment by Amelandbor** [comment]
Zip files will also mostly be fixed in 15.0, PR https://github.com/xbmc/xbmc/pull/6589 has been merged.

Will close this one now.
